### ISSUE TITLE
Infeasible instance solved as feasible

### ISSUE THREAD

**Issue by RichardLittmann** [coin-or/MibS#49]
After having the problem with infeasibilities in our bilevel program and posting it on Github (issue #45) you uploaded a new version which fixed this problem for the instance we supplied. We continued working on our model and unfortunately encountered a similar problem with a new instance.

Again, we had a upper level constraint of the form

d <= 0

with a lower level variable d and a lower level problem of the form

d = {max d , s.t. ...}

We tested an infeasible instance (mpsFile_original, auxFile_original). MibS deemed the instance to be feasibly solvable and put out a solution to the problem with d = 0 and corresponding feasible assignments of other upper level and lower level variables which however would lead to the lower level problem not being maximized (log_original). When we fixed the upper level variables to the MibS output and ran MibS again on this instance (mpsFile_fixed_0), MibS correctly detected the infeasibility of the problem. Also, when we changed the upper level constraint to

d <= 1000,

MibS found a solution to the lower level with a positive value (which now of course is feasible for the whole problem), although this was not detected before (log_fixed_1000). As our model essentially has several lower levels, there are several lower level variables that should make the upper level infeasible: 
y1,y2,y4,y5,y8. All of these have positive values and should therefore violate the respective <= 0 constraint (Dr14, DR17, DR4, DR6, DR9) in the upper level.

Unfortunately, we were not able to recreate this problem with a small toy example like the last time, so I am not sure whether it is easy to debug without deeper understanding of our BLP model. We checked our model several times and are quite certain that the results should differ from the solution by MibS. Should you need any info on the model or if you detect anything wrong with it which is problematic for MibS, we are happy to further discuss the issue.

Thank you once again for your great work on MibS. We are grateful for any help you can offer on this issue.

Kind regards,
Richard Littmann

[auxFile_fixed_0.txt](https://github.com/tkralphs/MibS/files/1687266/auxFile_fixed_0.txt)
[auxFile_fixed_1000.txt](https://github.com/tkralphs/MibS/files/1687267/auxFile_fixed_1000.txt)
[auxFile_original.txt](https://github.com/tkralphs/MibS/files/1687268/auxFile_original.txt)
[log_fixed_1000.txt](https://github.com/tkralphs/MibS/files/1687301/log_fixed_1000.txt)
[log_original.txt](https://github.com/tkralphs/MibS/files/1687270/log_original.txt)
[mpsFile_fixed_0.txt](https://github.com/tkralphs/MibS/files/1687278/mpsFile_fixed_0.txt)
[mpsFile_fixed_1000.txt](https://github.com/tkralphs/MibS/files/1687279/mpsFile_fixed_1000.txt)
[mpsFile_original.txt](https://github.com/tkralphs/MibS/files/1687280/mpsFile_original.txt)

**Comment by tkralphs** [comment]
To close the loop on this (sorry for not posting this earlier), the issue turned out to be due to a bug in the underlying [SYMPHONY](https://github.com/coin-or/SYMPHONY) solver, not a bug in MibS. You could try switching to [Cbc](https://github.com/coin-or/Cbc) if it persists.
