### ISSUE TITLE
Can’t find MibS/build/bin/mibs

### ISSUE THREAD

**Issue by BecarefulNN** [coin-or/MibS#58]
hi, i meet a problem. when i finish installed Mibs in windows, i can't find this path.
only five **.exe** file in this directory, just like the picture shows.
![1](https://user-images.githubusercontent.com/10435339/38919208-88ec80a6-4322-11e8-9061-925179e7e87f.png)
i don't know how to fix it. please show a bright way to me. thanks a lot.

sincerely
a user  : )

**Comment by tkralphs** [comment]
The file `mibs.exe` _is_ the executable on Windows. On other platforms, the binary doesn't have an extension. Hope this answers the question for you!
