### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by posseidon23** [coin-or/MibS#59]
Hi, 
I downloaded the Mibs package, and when trying to install on my computer (mac os X) I have the error message : 
BuildTools/get.dependencies.sh: line 656: declare: -A: invalid option
Any ideas please about the issue?
Thanks

**Comment by tkralphs** [comment]
I am aware of this issue and unfortunately, I don't know of an easy fix from our side. The problem is that the version of bash that comes with OS X is very outdated. If you install a more recent version with homebrew, everything should work fine.

**Comment by posseidon23** [comment]
Thank you. I ll try this.

**Comment by tkralphs** [comment]
I guess this worked so I'm closing this issue.
