### ISSUE TITLE
Installation issue in last step

### ISSUE THREAD

**Issue by ShraddhaBG** [coin-or/MibS#76]
Hi

The steps to Configure, Build, Run and Install for Blas 1.4, Lapack 1.5 are completed.
There is an error in Running CoinUtils as follows. Any idea to solve this issue and move further? Thanks in advance.

##################################################
##################################################

Testing CoinFinite ...  finite value: ok; infinite value: ok.
Testing CoinIsnan ...  finite value: ok; NaN value: ok.
Testing CoinModel
Assertion failed: numErr== 0, file C:/MSYS64/home/DELL/coinbrew/CoinUtils/CoinUtils/test/CoinModelTest.cpp, line 447
make[1]: *** [Makefile:600: test] Error 3
make: *** [Makefile:819: test] Error 2

Build failed, see error output above

**Comment by tkralphs** [comment]
It would be good to know why the CoinUtils unit test is failing, but it's unlikely yo be anything that will affect MibS. For now, you can just call coinbrew with `--tests none` and it should go through.

**Comment by tkralphs** [comment]
If you don't mind, you could open an issue at https://github.com/coin-olr/CoinUtils for the unit test failure. Just make sure to give details, such as platform, compiler, etc.

**Comment by ShraddhaBG** [comment]
> It would be good to know why the CoinUtils unit test is failing, but it's unlikely yo be anything that will affect MibS. For now, you can just call coinbrew with `--tests none` and it should go through.

Reolved after building with '--test none'. Thank you!

**Comment by ShraddhaBG** [comment]
> If you don't mind, you could open an issue at https://github.com/coin-olr/CoinUtils for the unit test failure. Just make sure to give details, such as platform, compiler, etc.

Sure! Will do that.
