### ISSUE TITLE
Installation issue in the building step

### ISSUE THREAD

**Issue by evanspuck** [coin-or/MibS#83]
Hi, I'm using macOS Catalina, and when I build the 1.1.3 version with "--test non", I receive the following error massages in the step of building MibS:

/Users/mac/coinbrew/MibS/src/MibSCutGenerator.cpp:2239:52: error: no member named 'deletePrunedNodes' in 'AlpsParams'; did you mean 'deleteDeadNode'? ...boundModel->AlpsPar()->setEntry(AlpsParams::deletePrunedNodes, true);

/Users/mac/coinbrew/MibS/src/MibSCutGenerator.cpp:2318:40: error: no member named 'getWorkingSubTree' in 'AlpsKnowledgeBrokerSerial' AlpsSubTree *boundProbTree = broker.getWorkingSubTree();

Then the build just failed.

Thank you very much!

Best,
Evans Cai

**Comment by tkralphs** [comment]
I guess you are somehow using the wrong version of Alps. MibS depends on `stable/1.5`, which has that parameter, but `stable/2.0` does not. I'm not sure how you got the individual repos, but if you use `coinbrew`, everything. If you want to do this manually, just make sure to look at the Dependencies file and get the right versions.

**Comment by evanspuck** [comment]
> I guess you are somehow using the wrong version of Alps. MibS depends on `stable/1.5`, which has that parameter, but `stable/2.0` does not. I'm not sure how you got the individual repos, but if you use `coinbrew`, everything. If you want to do this manually, just make sure to look at the Dependencies file and get the right versions.

Successfully installed, thanks a lot!
