### ISSUE TITLE
Write the solution to a file

### ISSUE THREAD

**Issue by odow** [coin-or/MibS#89]
It would be very handy if there was an option to write the solution to a file (in a structured manner) instead of printing it to `stdout`.

**Comment by tkralphs** [comment]
This should be pretty easy, thanks for the suggestion.

**Comment by tkralphs** [comment]
This is added in 4cf4c56. It will be in release 1.2.0, which should be coming out next weekish.

**Comment by tkralphs** [comment]
Let me know if you want some change to the format to make it easier to parse. Right now, we have first- and second-level variables in different sections with each line being `varName = varValue`. See #115 .

**Comment by odow** [comment]
One variable per line is okay.
