### ISSUE TITLE
How to use CPLEX?

### ISSUE THREAD

**Issue by gguillot** [coin-or/MibS#90]
Hi,
I want to use CPLEX instead of SYMPHONY, I changed the config file, but I can't link the solver.
Do you know what needs to be changed to link the solver? 

Thank you.

**Comment by tkralphs** [comment]
Assuming you are building from source with `coinbrew`, you have to tell MibS where to find CPLEX. For example, I build as follows on our cluster. 
```
coinbrew build MibS --with-cplex-incdir=/usr/local/cplex/include/ilcplex --with-cplex-lib="-L/usr/local/cplex/lib/x86-64_linux/static_pic/ -lcplex -lpthread -lm"
```
Then, set the solver to CPLEX with the option `-MibS_feasCheckSolver CPLEX`. Let me know how it goes.

**Comment by tkralphs** [comment]
I'm going to move this to a Discussion instead of an Issue, since it's more of question than a problem.
