### ISSUE TITLE
Mistake in Documentation

### ISSUE THREAD

**Issue by gtjusila** [coin-or/MibS#93]
Dears,

I think the optimal solution for the general example in the documentation for creating the MPS and Auxiliary file found [here](https://coral.ise.lehigh.edu/wp-content/uploads/2016/02/MibS_inputFile.pdf) is incorrect. The solution C0 = 10 and C1 = 5 does not fulfills the lower level constraint 2*C0 - C1 <= 7. MibS optimal solution here is C0 = 6 and C1 = 5. Much Thanks!

Best Regards,
Gennesaret Tjusila

**Comment by tkralphs** [comment]
Indeed, you are correct! I'm in the midst of creating some better documentation in preparation for an new release, so I will fix this, thanks. Stay tuned, I'll let you know.

**Comment by tkralphs** [comment]
OK, I have now posted some improved documentation, which has the same example, but with the correct solution now:

https://coin-or.github.io/MibS

Thanks!
